### ISSUE TITLE
ReferenceError: useSSRContext is not defined

### ISSUE THREAD

**Issue by Carloosolrac** [galvez/fastify-vite-vue-hackernews#1]
First at all, thanks for tutorial, I learned a lot.

When I try to test your code with `npm run dev` I got:

```
ReferenceError: useSSRContext is not defined
    at setup (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/entry/base.vue:55:34)
    at _sfc_main.setup (/entry/base.vue:124:23)
    at callWithErrorHandling (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7090:29)
    at setupComponent (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7046:11)
    at renderComponentVNode (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:185:17)
    at /Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:443:30
    at Generator.next (<anonymous>)
    at /Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:31:71
    at new Promise (<anonymous>)
```

Also happen with `npm run serve`, but in this way I can see the site.

**Comment by ubzor** [comment]
> First at all, thanks for tutorial, I learned a lot.
> 
> When I try to test your code with `npm run dev` I got:
> 
> ```
> ReferenceError: useSSRContext is not defined
>     at setup (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/entry/base.vue:55:34)
>     at _sfc_main.setup (/entry/base.vue:124:23)
>     at callWithErrorHandling (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
>     at setupStatefulComponent (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7090:29)
>     at setupComponent (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7046:11)
>     at renderComponentVNode (/Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:185:17)
>     at /Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:443:30
>     at Generator.next (<anonymous>)
>     at /Users/mymac/Projects/JS/fastify-vite-vue-hackernews-main/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:31:71
>     at new Promise (<anonymous>)
> ```
> 
> Also happen with `npm run serve`, but in this way I can see the site.

you need to add `import { useSSRContext } from 'vue'` to `entry/base.vue` file
